version: '3'

services:
  mysql:
    container_name: ${CONTAINER_DB_NAME}
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DB_PATH}:/var/lib/mysql

  php:
    depends_on:
      - mysql
    container_name: ${CONTAINER_PHP_NAME}
    build: ./docker-php
    restart: unless-stopped
    volumes:
      - ${CODE_PATH}:/code
      - ${PHP_LOG_CONF_PATH}:/usr/local/etc/php-fpm.d/zz-log.conf

  web:
    depends_on:
      - php
    container_name: ${CONTAINER_WEB_NAME}
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ${CODE_PATH}:/code
      - ${SITE_CONF_PATH}:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
  default:
    external:
      name: ${NETWORK}
